#server:
#  port: 8080
#spring:
#  application:
#    name: spring-security-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: path_route
#          uri: http://127.0.0.1:8089
#          predicates:
#            - Path=/oath/login
#          filters:
#            - StripPrefix=1
##